module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert("Users", [
      {
        createdAt: new Date(),
        updatedAt: new Date(),
        name: "Kevin-Khoi",
        avatar: "https://randomuser.me/api/portraits/women/51.jpg",
        age: 1,
      },
      {
        createdAt: new Date(),
        updatedAt: new Date(),
        name: "Lora Hahn MD",
        avatar: "https://randomuser.me/api/portraits/women/52.jpg",
        age: 1,
      },
      {
        createdAt: new Date(),
        updatedAt: new Date(),
        name: "Leonard Swift",
        avatar: "https://randomuser.me/api/portraits/women/53.jpg",
        age: 12,
      },
      {
        createdAt: new Date(),
        updatedAt: new Date(),
        name: "Guadalupe Langosh",
        avatar: "https://randomuser.me/api/portraits/women/54.jpg",
        age: 97,
      },
      {
        createdAt: new Date(),
        updatedAt: new Date(),
        name: "Angela Aufderhar",
        avatar: "https://randomuser.me/api/portraits/women/55.jpg",
        age: 30,
      },
      {
        createdAt: new Date(),
        updatedAt: new Date(),
        name: "Domingo Torp Jr.",
        avatar: "https://randomuser.me/api/portraits/women/56.jpg",
        age: 67,
      },
      {
        createdAt: new Date(),
        updatedAt: new Date(),
        name: "Joyce Reichert",
        avatar: "https://randomuser.me/api/portraits/women/57.jpg",
        age: 66,
      },
      {
        createdAt: new Date(),
        updatedAt: new Date(),
        name: "Yvonne Koelpin",
        avatar: "https://randomuser.me/api/portraits/women/58.jpg",
        age: 78,
      },
      {
        createdAt: new Date(),
        updatedAt: new Date(),
        name: "Chester Mertz",
        avatar: "https://randomuser.me/api/portraits/women/59.jpg",
        age: 62,
      },
      {
        createdAt: new Date(),
        updatedAt: new Date(),
        name: "Miss Rita Schumm",
        avatar: "https://randomuser.me/api/portraits/women/60.jpg",
        age: 53,
      },
      {
        createdAt: new Date(),
        updatedAt: new Date(),
        name: "Jane Hand",
        avatar: "https://randomuser.me/api/portraits/women/61.jpg",
        age: 2,
      },
      {
        createdAt: new Date(),
        updatedAt: new Date(),
        name: "Everett Hansen",
        avatar: "https://randomuser.me/api/portraits/women/62.jpg",
        age: 0,
      },
      {
        createdAt: new Date(),
        updatedAt: new Date(),
        name: "Roland Hand",
        avatar: "https://randomuser.me/api/portraits/women/63.jpg",
        age: 59,
      },
      {
        createdAt: new Date(),
        updatedAt: new Date(),
        name: "Kendra Hamill Jr.",
        avatar: "https://randomuser.me/api/portraits/women/64.jpg",
        age: 8,
      },
      {
        createdAt: new Date(),
        updatedAt: new Date(),
        name: "Edgar Skiles",
        avatar: "https://randomuser.me/api/portraits/women/65.jpg",
        age: 33,
      },
      {
        createdAt: new Date(),
        updatedAt: new Date(),
        name: "Tamara Mohr",
        avatar: "https://randomuser.me/api/portraits/women/66.jpg",
        age: 20,
      },
      {
        createdAt: new Date(),
        updatedAt: new Date(),
        name: "Marianne Friesen",
        avatar: "https://randomuser.me/api/portraits/women/67.jpg",
        age: 61,
      },
      {
        createdAt: new Date(),
        updatedAt: new Date(),
        name: "Ida Casper",
        avatar: "https://randomuser.me/api/portraits/women/68.jpg",
        age: 85,
      },
      {
        createdAt: new Date(),
        updatedAt: new Date(),
        name: "Miss Lloyd Legros",
        avatar: "https://randomuser.me/api/portraits/women/69.jpg",
        age: 70,
      },
      {
        createdAt: new Date(),
        updatedAt: new Date(),
        name: "Sue Schimmel",
        avatar: "https://randomuser.me/api/portraits/women/70.jpg",
        age: 75,
      },
      {
        createdAt: new Date(),
        updatedAt: new Date(),
        name: "Inez Jaskolski",
        avatar: "https://randomuser.me/api/portraits/women/71.jpg",
        age: 57,
      },
    ]);
  },
  down: (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete("Users", null, {});
  },
};
